name: CI/CD Build

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Maven - Regular Build
        working-directory: ./maven-project
        run: ./mvnw clean verify

      - name: Maven - Native Test
        working-directory: ./maven-project
        run: ./mvnw clean verify -DskipITs=false

      - name: Gradle - Regular Build
        working-directory: ./gradle-project
        run: ./gradlew clean build

      - name: Gradle - Quarkus Int Test
        working-directory: ./gradle-project
        run: ./gradlew quarkusIntTest
